# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mothers_maiden_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='communication_means1',
            field=models.NullBooleanField(verbose_name='Use Phone As Prefered Means Of Communication'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='communication_means2',
            field=models.NullBooleanField(verbose_name='Use E-mail As Prefered Means Of Communication'),
        ),
    ]
