# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0005_sentmail_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='from_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sentmail',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
