# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0007_auto_20180218_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_url',
            field=models.CharField(max_length=400),
        ),
    ]
