# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0008_auto_20180218_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTextCordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.PositiveIntegerField()),
                ('right', models.PositiveIntegerField()),
                ('bottom', models.PositiveIntegerField()),
                ('left', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=700)),
                ('alt_text', models.CharField(max_length=400)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='compunetcrm.UploadedImage')),
            ],
        ),
    ]
