# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0010_auto_20180220_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetextcordinate',
            name='bottom',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='imagetextcordinate',
            name='left',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='imagetextcordinate',
            name='right',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='imagetextcordinate',
            name='top',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
    ]
