# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0012_auto_20180220_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetextcordinate',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compunetcrm.UploadedImage'),
        ),
    ]
