# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0013_auto_20180220_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetextcordinate',
            old_name='image',
            new_name='imagelink',
        ),
    ]
