# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0014_auto_20180220_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmail',
            name='from_email',
        ),
        migrations.AddField(
            model_name='sentmail',
            name='delivery_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 20, 23, 29, 6, 62895, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
