# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0015_auto_20180220_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='image_sent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='compunetcrm.UploadedImage'),
        ),
    ]
