# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0019_auto_20180221_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_text_xandy_cordinate',
        ),
    ]
