# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0020_remove_uploadedimage_image_text_xandy_cordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(max_length=15, verbose_name='Sent To')),
                ('sent_by', models.CharField(max_length=45, verbose_name='Sent By')),
                ('cost', models.DecimalField(decimal_places=7, max_digits=20)),
                ('message_id', models.CharField(max_length=45, verbose_name='Sent By')),
                ('status', models.CharField(max_length=15, verbose_name='Sent To')),
            ],
        ),
    ]
