# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0021_sentsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentsms',
            name='cost',
            field=models.CharField(max_length=15, verbose_name='Sms Cost'),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='sent_by',
            field=models.CharField(blank=True, max_length=45, verbose_name='Sent By'),
        ),
    ]
