# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compunetcrm', '0022_auto_20180227_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentsms',
            name='message_body',
            field=models.CharField(blank=True, max_length=800, verbose_name='Message Body'),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='status',
            field=models.CharField(max_length=15, verbose_name='Delivery Status'),
        ),
    ]
